version: v1.0
projects:
- app_name: chainstory
  app_path: /server
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    preview: true
    paths:
    - /
    ignore_paths:
    - vendor
    - build
    - bin
    exts:
    - .go
